import Container from '@mui/material/Container';

import 'react-tabs/style/react-tabs.css';
import React, {useState, useEffect} from 'react';
import {Client} from '@stomp/stompjs';
import {SOCKET_URL} from '../constants/Constants';
import {Grid, Button, Paper, CssBaseline, ThemeProvider, Tooltip} from '@mui/material';
import {Form, Field} from 'react-final-form';
import {centerHorizontal, inputStyles, mockQrFragment, mockScanContent} from '../styling/Custom';
import {getLocalStationTheme} from '../util/ThemeUtils';
import toast from 'react-hot-toast';
import InfoIcon from '@mui/icons-material/Info';
import {Server} from '../api/Server';
import {useTranslation} from 'react-i18next';

let stompClient: any;

export function MockQr() {

    const {t} = useTranslation()


    const [qrCode, setQrCode] = useState<string | undefined>(undefined)
    const [customQrCode, setCustomQrCode] = useState<string | undefined>(undefined)

    useEffect(() => {

        stompClient = new Client({
            brokerURL: SOCKET_URL,
            onConnect: () => {
                console.log("Websocket client connected, listening for Mock QR events.")

                stompClient.subscribe("/websocket/mockGen", (message: any) => {
                    setQrCode(message.body)
                })

            },
            onWebSocketClose: () => {
                console.error("Websocket closed!")
            }
        })

        stompClient.activate();

    }, []);

    function getCustomQr(customQrData: any) {

        Server.getCustomQrCode(customQrData, (customQrCode) => {
            setCustomQrCode(customQrCode)
        })
    }

    function sendMockScannedQrData(formValues) {

        const mockQrRequest = {
            mockScannedQr: formValues?.mockScannedQR?.toUpperCase()
        }

        Server.sendMockQr(mockQrRequest, (error) => {
            toast.error(t("msg_errorSendingMockQr"))
        })
    }

    return (
        <ThemeProvider theme={getLocalStationTheme()}>
            <CssBaseline/>
            <Container style={centerHorizontal}>
                <Grid style={centerHorizontal}>
                    <Form onSubmit={getCustomQr}
                          render={({handleSubmit, form, submitting, pristine, values}) => {

                              let formValid: boolean = values && values.customQr;

                              return (
                                  <form onSubmit={handleSubmit}>
                                      <Grid style={{...centerHorizontal, minHeight: 252}}>
                                          <Paper style={mockQrFragment}>
                                              <h3>{t("nextAutoGeneratedQr")}

                                                  <Tooltip title={t("autoGeneratedQrWithSubsequentNumber")}>
                                                      <InfoIcon/>
                                                  </Tooltip>
                                              </h3>

                                              {qrCode &&
                                                  <img src={"data:image/jpg;base64," + qrCode} alt="Next QR Code"/>}
                                          </Paper>
                                      </Grid>
                                      <Grid style={{...centerHorizontal, minHeight: 252}}>
                                          <Grid>
                                              <Paper style={mockQrFragment}>

                                                  <h3>{t("qrGeneratedOnDemand")}
                                                      <Tooltip title={t("qrGeneratedOnDemandToolTip")}>
                                                          <InfoIcon/>
                                                      </Tooltip>
                                                  </h3>
                                                  {customQrCode &&
                                                      <img src={"data:image/jpg;base64," + customQrCode}
                                                           alt="Custom QR Code"/>}
                                                  <Field name="customQr" component="input"/>

                                                  <Button variant="text" type="button" disabled={!formValid}
                                                          onClick={() => {
                                                              getCustomQr(values.customQr.toUpperCase())
                                                          }}>{t("generateAction")}</Button>
                                              </Paper>
                                          </Grid>


                                      </Grid>

                                  </form>)
                          }}>
                    </Form>
                </Grid>
                <Grid style={centerHorizontal}>
                    <Paper style={mockScanContent}>

                        <Form onSubmit={sendMockScannedQrData}
                              mutators={{
                                  setFormAttribute: ([fieldName, fieldVal], state, {changeValue}) => {
                                      changeValue(state, fieldName, () => fieldVal);
                                  }
                              }}
                              render={({handleSubmit, form, submitting, pristine, values}) => {

                                  return (
                                      <form onSubmit={handleSubmit}>
                                          <Grid container spacing={2} direction="column" alignItems="center">

                                              <Grid sx={inputStyles}>
                                                  <label>{t("mockBarcodeQr")}
                                                      <Tooltip title={t("mockBarcodeQrTooltip")}>
                                                          <InfoIcon/>
                                                      </Tooltip>
                                                  </label>
                                                  <Field name="mockScannedQR" component="input"/>
                                              </Grid>
                                              <Grid>
                                                  <Button variant="text" type='submit'
                                                          disabled={!values.mockScannedQR}>{t("sendAction")}</Button>
                                              </Grid>
                                          </Grid>
                                      </form>)
                              }}>
                        </Form>
                    </Paper>
                </Grid>
            </Container>
        </ThemeProvider>
    );
}
